# 각 섹션에 대한 설명은 별도 문서를 작성하여 제공, 인라인 주석은 사용X
[server]
port = 41924

[log]
path = ../logs/sstd.log

[security]
hmac_key = "3e4a4f4e055213dff116d80da6fa3bbdd580665bcc99328bffe0502ec709f470"

[proxy]
host = sstd.phob.site
port = 443
interface = "ens160"